data_dtypes = {}
mobility_dtypes = {"placekey": "object",
                   "safegraph_place_id": "object",
                   "parent_placekey": "object",
                   "parent_safegraph_place_id": "object",
                   "location_name": "category",
                   "street_address": "category",
                   "city": "category",
                   "region": "category",
                   "postal_code": "int32",
                   "safegraph_brand_ids": "object",
                   "brands": "category",
                   "date_range_start": "object",
                   "date_range_end": "object",
                   "raw_visit_counts": "int64",
                   "raw_visitor_counts": "int64"}
